services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: zaverecne_zadanie
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    depends_on:
      - db
    env_file:
      - backend/.env
    environment:
      DATABASE_URL: mysql+aiomysql://root:root@db:3306/zaverecne_zadanie?charset=utf8mb4
      SECRET_KEY: mojtajnykluc
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 60
    ports:
      - "127.0.0.1:8000:8000"
    working_dir: /app

  # nginx:
  #   image: nginx:latest
  #   depends_on:
  #     - backend
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./frontend:/usr/share/nginx/html
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  db_data: